#choice save data
#Thu Mar 12 17:06:02 KST 2026
clues=찢어진 악보
currentSceneId=music_torn_sheet
evidence.찢어진\ 악보=확보
finalChoice=
musicSolved=false
playerName=ㅓㅓ
poolSolved=false
scienceSolved=false
seenEndings=
suspectHistory=
suspicionScore=0
textSpeedMs=18
truthScore=0
visitedScenes=prologue_arrival|prologue_principal|prologue_nurse|prologue_hall|case_hub|music_intro|music_torn_sheet
